### ISSUE TITLE
+ Button: change: tap on anythign but +Button elements will bring out of overlay state

### ISSUE THREAD

**Issue by danlatorre** [thewisecity/declarehome-android#16]
Currently on Oct 27&28 builds, if I tap on the screen it I get and OSD blurb, 'you tapped X'. Let's remove this and make it physically match the overlay logic: tapping any where brings you back to the wall viewing

**Comment by danlatorre** [comment]
Here's the screen shot: https://www.dropbox.com/s/89vjqu2fb7qmb53/Screenshot_2015-10-27-19-57-40.png?dl=0

**Comment by danlatorre** [comment]
this is also happening on the "choose groups" step in the Post Alert feature, tapping in the White area brings the notification overaly "you tapped [message post text]"

**Comment by dexterlohnes** [comment]
Fixed in 7563f1b
