### ISSUE TITLE
Alerts: show chosen alert category on step 2 group select

### ISSUE THREAD

**Issue by danlatorre** [thewisecity/declarehome-android#7]

**Comment by dexterlohnes** [comment]
What does this mean Daniel? Please provide more info and screens

**Comment by danlatorre** [comment]
In this screen shot again: 
https://www.dropbox.com/s/lgf6kp3xfcsho4a/Screenshot%202015-10-23%2001.08.18.png?dl=0

2nd screen shows:
Alert type: [type]

You have this in the app but it isn't showing the alert types, e.g.

Alert type: Crisis Alert

Intention: confirm to user that item selected in step 1 is correct and for context on which groups are relevant to select.... people get interrupted all that time... look  away from screen and need reminder in UI to say this is what  you selected

**Comment by dexterlohnes** [comment]
Fixed in 3abb01e
